
name : Update Dependencies

on :
    workflow_dispatch :

jobs :
    update :

        runs-on : ubuntu-latest

        steps :

            -   name : Checkout Repository
                uses : actions/checkout@v4

            -   name : Update & Dependencies
                run : ./.github/scripts/Update-Dependencies.sh
